library(openxlsx)
datac <- read.xlsx("D:/surveydataset.xlsx")
datae <- read.xlsx("D:/surveydataset.xlsx", sheet=2)
inputc <- datac[,c('rank_UA','rank_JD','rank_NB','rank_VANS','rank_ASICS')]
head(inputc)
inpute <- datae[,c('rank_UA','rank_JD','rank_NB','rank_VANS','rank_ASICS')]
head(inpute)
inputcc <- na.omit(inputc)
inputcc$rank_NB <- as.numeric(inputcc$rank_NB)
inputcc$rank_UA <- as.numeric(inputcc$rank_UA)
inputcc$rank_JD <- as.numeric(inputcc$rank_JD)
inputcc$rank_ASICS <- as.numeric(inputcc$rank_ASICS)
library(ggplot2)
ggplot(inputcc,aes(x=rank_NB, y=(..count..)/sum(..count..)))+
  geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count")+
  ggtitle("New Balance Control")+
  scale_y_continuous(labels = scales::percent)+
  geom_text(aes(label = scales::percent(..prop..), y= ..prop.. ), stat= "count", vjust = -.5)+
  labs(x="Rank NB C", y = "Percent", fill="rank_NB")
library(xlsx)
control <- read.xlsx("/Users/mac-nw/Documents/525-51/project/surveydataset.xlsx", sheetIndex=1, header=TRUE)
experimental <- read.xlsx("/Users/mac-nw/Documents/525-51/project/surveydataset.xlsx", sheetIndex=2, header=TRUE)
str(control)
str(experimental)
#control <- control[complete.cases(control), ]
#if we clear NA value, control group only has 12 obs.
#experimental <- experimental[complete.cases(experimental), ]
#if we clear NA value, experimental group only has 4 obs. 
summary(control)
summary(experimental)
control["group"] <- "control"
experimental["group"] <- "experimental"
total <- rbind(control, experimental)
total[total=="x"] <- NA
summary(total)
prop.table(table(total$brand_image_affect))
total$rank_UA <- factor(total$rank_UA)
total$rank_JD <- factor(total$rank_JD)
total$rank_VANS <- factor(total$rank_VANS)
total$rank_NB <- factor(total$rank_NB)
total$rank_ASICS <- factor(total$rank_ASICS)
with(total,table(group,rank_UA))
with(total,table(group,rank_JD))
with(total,table(group,rank_VANS))
with(total,table(group,rank_NB))
with(total,table(group,rank_ASICS))
with(total, chisq.test(rank_UA, group))
with(total, chisq.test(rank_JD, group))
with(total, chisq.test(rank_VANS, group))
with(total, chisq.test(rank_NB, group))
with(total, chisq.test(rank_ASICS, group))
with(total,table(group,UA_perf))
with(total,table(group,UA_price))
with(total,table(group,UA_visual))
with(total,table(group,UA_comfort))
with(total, chisq.test(UA_perf, group))
with(total, chisq.test(UA_price, group))
with(total, chisq.test(UA_visual, group))
with(total, chisq.test(UA_comfort, group))
with(total,table(group,JD_perf))
with(total,table(group,JD_price))
with(total,table(group,JD_visual))
with(total,table(group,JD_comfort))
with(total, chisq.test(JD_perf, group))
with(total, chisq.test(JD_price, group))
with(total, chisq.test(JD_visual, group))
with(total, chisq.test(JD_comfort, group))
with(total,table(group,VANS_perf))
with(total,table(group,VANS_price))
with(total,table(group,VANS_visual))
with(total,table(group,VANS_comfort))
with(total, chisq.test(VANS_perf, group))
with(total, chisq.test(VANS_price, group))
with(total, chisq.test(VANS_visual, group))
with(total, chisq.test(VANS_comfort, group))
with(total,table(group,NB_perf))
with(total,table(group,NB_price))
with(total,table(group,NB_visual))
with(total,table(group,NB_comfort))
with(total, chisq.test(NB_perf, group))
with(total, chisq.test(NB_price, group))
with(total, chisq.test(NB_visual, group))
with(total, chisq.test(NB_comfort, group))
with(total,table(group,ASICS_perf))
with(total,table(group,ASICS_price))
with(total,table(group,ASICS_visual))
with(total,table(group,ASICS_comfort))
with(total, chisq.test(ASICS_perf, group))
with(total, chisq.test(ASICS_price, group))
with(total, chisq.test(ASICS_visual, group))
with(total, chisq.test(ASICS_comfort, group))
total$rank_UA_lm <- as.numeric(total$rank_UA)
total$gender_lm <- factor(total$gender)
total$age_lm <- factor(total$age)
total$race_lm <- factor(total$race)
total$brand_image_affect_lm <- factor(total$brand_image_affect)
total$group_lm <- factor(total$group)
lmmodelful <- lm(rank_UA_lm ~ gender_lm*age_lm*race_lm*brand_image_affect_lm*group_lm, data=total)
lmmodelinteraction <- lm(rank_UA_lm ~ 
  (gender_lm+age_lm+race_lm++brand_image_affect_lm+group_lm)^4, data=total)
lmmodelint <- lm(rank_UA_lm ~  gender_lm+age_lm+race_lm+
  brand_image_affect_lm+group_lm, data=total)
anova(lmmodelful,lmmodelinteraction,lmmodelint)
summary(lmmodelint)
total$rank_NB_lm <- as.numeric(total$rank_NB)
lmmodelint_NB <- lm(rank_NB_lm ~ gender_lm+age_lm+race_lm+brand_image_affect_lm+group_lm, data=total)
summary(lmmodelint_NB)
